[package]
name = "flexible-project-core"
version = "0.0.0"
description = "Flexible Project core library"
authors = ["tuguzT <timurka.tugushev@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
edition = "2021"
