[package]
name = "flexible-project-workspace"
description = "Flexible Project workspace backend microservice binary"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
