[package]
name = "flexible-project-core"
version = "0.0.0"
description = "Flexible Project domain layer library"
authors = ["tuguzT <timurka.tugushev@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "../../README.md"
repository = "https://github.com/tuguzT/flexible-project"
edition = "2021"
