[package]
name = "flexible-project-user-domain"
version = "0.0.0"
description = "Flexible Project backend user microservice domain layer library"
authors = ["tuguzT <timurka.tugushev@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tuguzT/flexible-project"
edition = "2021"

[dependencies]
fp-core = { package = "flexible-project-core", path = "../flexible-project-core" }
async-trait = "0.1.67"
auto_impl = "1.0.1"
derive_more = "0.99.17"
once_cell = "1.17.1"
fancy-regex = "0.11.0"
typed-builder = "0.14.0"
