[package]
name = "flexible-project-user"
description = "Flexible Project backend user microservice binary"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
domain = { package = "flexible-project-user-domain", path = "../flexible-project-user-domain" }
data = { package = "flexible-project-user-data", path = "../flexible-project-user-data" }
