[package]
name = "flexible-project-gateway"
description = "Flexible Project backend API Gateway microservice binary"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
