[package]
name = "flexible-project-data"
version = "0.0.0"
description = "Flexible Project data layer library"
authors = ["tuguzT <timurka.tugushev@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/tuguzT/flexible-project"
edition = "2021"

[dependencies]
fp-core = { path = "../flexible-project-core", package = "flexible-project-core", version = "0.0.0" }
async-trait = "0.1.57"
serde = { version = "1.0.144", features = ["derive"] }
